<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 .\city.glb -T -d /draco/
-->

<script>
  import { T } from "@threlte/core";
  import { InstancedMesh, useDraco, useGltf } from "@threlte/extras";

  import { AutoColliders } from "@threlte/rapier";

  import PlayerController from "./gameController/playerController.svelte";
  import GasStation from "./world/GasStation.svelte";
  import Building1 from "./world/city/Building1.svelte";
  import Building10 from "./world/city/Building10.svelte";
  import Building2 from "./world/city/Building2.svelte";
  import Building3 from "./world/city/Building3.svelte";
  import Building4 from "./world/city/Building4.svelte";
  import Building5 from "./world/city/Building5.svelte";
  import Building6 from "./world/city/Building6.svelte";
  import Building7 from "./world/city/Building7.svelte";
  import Building8 from "./world/city/Building8.svelte";
  import Building9 from "./world/city/Building9.svelte";
  import Bolta from "./world/city/Building_Bolta.svelte";
  import Globo from "./world/city/Globo.svelte";
  import Shop from "./world/shop/Shop.svelte";
  //   import Help from "./help/Help.svelte";
  import Station from "./world/Station.svelte";
  import Houses from "./world/houses/Houses.svelte";
  import Road from "./world/road/Road.svelte";
  import Park from "./world/park/Park.svelte";
  import Water from "./world/water/Water.svelte";

  import FlyingCarSpawner from "./car/FlyingCarSpawner.svelte";

  let {
    fallback = () => {},
    error = () => {},
    children = () => {},
    ref = $bindable(),
    ...props
  } = $props();

  const gltf = useGltf("/city-transformed.glb", { dracoLoader: useDraco() });
</script>

<InstancedMesh>
  <PlayerController />

  <Bolta />
  <Globo />
  <Park />
  <Houses />
  <Shop />
  <!-- <Help /> -->
  <Station />
  <Building1 />
  <Building2 />
  <Building3 />
  <Building4 />
  <Building5 />
  <Building6 />
  <Building7 />
  <Building8 />
  <Building9 />
  <Building10 />
  <GasStation />
  <Water />
  <Road />

  <FlyingCarSpawner
    start={{ x: -150, y: 25, z: -24 }}
    end={{ x: 150 }}
    rotation={[0, Math.PI / 2, 0]}
  />

  <FlyingCarSpawner
    start={{ x: 150, y: 25, z: 24 }}
    end={{ x: -150 }}
    rotation={[0, Math.PI * 1.5, 0]}
  />
</InstancedMesh>

<T.Group bind:ref dispose={false} {...props}>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <AutoColliders shape="convexHull">
      <T.Mesh
        position={[0, 0.1, 0]}
        geometry={gltf.nodes.general_ground.geometry}
        material={gltf.nodes.general_ground.material}
      />
    </AutoColliders>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
